export const Actions = {
    Users: {
        GET_USERS: "GET_USERS",
        GET_USERS_SUCCESS: "GET_USERS_SUCCESS"
    },
    User: {
        GET_USER: "GET_USER",
        GET_USER_SUCCESS: "GET_USER_SUCCESS",
        SET_USER: "SET_USER",
        SAVE_USER: "SAVE_USER",
        SAVE_USER_SUCCESS: "SAVE_USER_SUCCESS",
        DELETE_USER: "DELETE_USER",
        DELETE_USER_SUCCESS: "DELETE_USER_SUCCESS",
        ADD_GROUP: "ADD_GROUP_TO_USER",
        ADD_GROUP_SUCCESS: "ADD_GROUP_TO_USER_SUCCESS",
    },  
    Groups: {
        GET_GROUPS: "GET_GROUPS",
        GET_GROUPS_SUCCESS: "GET_GROUPS_SUCCESS"
    },
    Group: {
        GET_GROUP: "GET_GROUP",
        GET_GROUP_SUCCESS: "GET_GROUP_SUCCESS",
        SET_GROUP: "SET_GROUP",
        SAVE_GROUP: "SAVE_GROUP",
        SAVE_GROUP_SUCCESS: "SAVE_GROUP_SUCCESS",
        DELETE_GROUP: "DELETE_GROUP",
        DELETE_GROUP_SUCCESS: "DELETE_GROUP_SUCCESS",
    }
};
